apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.statistics.service.metadata.name }}
spec:
  selector:
    app: {{ .Values.statistics.service.selector.app }}
  ports:
    - name: "{{ .Values.statistics.service.ports.name }}"
      port: {{ .Values.statistics.service.ports.port }}
      targetPort: {{ .Values.statistics.service.ports.targetPort }}

