apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.frontend.deployment.metadata.name }}
  name: {{ .Values.frontend.deployment.metadata.name }}
  namespace: {{ .Values.frontend.deployment.metadata.namespace }}
spec:
  replicas: {{ .Values.frontend.deployment.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.deployment.metadata.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.frontend.deployment.metadata.name }}

    spec:
      containers:
        - name: {{ .Values.frontend.deployment.metadata.name }}
          image: "{{ .Values.frontend.deployment.template.spec.containers.image.name }}:{{ .Values.frontend.deployment.template.spec.containers.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.deployment.template.spec.containers.image.PullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.frontend.deployment.template.spec.containers.resources.cpu.requests }}
              memory: {{ .Values.frontend.deployment.template.spec.containers.resources.memory.requests }}
            limits:
              cpu: {{ .Values.frontend.deployment.template.spec.containers.resources.cpu.limits }}
              memory: {{ .Values.frontend.deployment.template.spec.containers.resources.memory.limits }}
          ports:
            - name: {{ .Values.frontend.deployment.template.spec.containers.ports.name }}
              containerPort: {{ .Values.frontend.deployment.template.spec.containers.ports.port }}
              protocol: {{ .Values.frontend.deployment.template.spec.containers.ports.protocol }}
