apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.metadata.name }}
spec:
  selector:
    app: frontend
  ports:
    - name: {{ .Values.frontend.service.spec.ports.name }}
      port: {{ .Values.frontend.service.spec.ports.port }}
      targetPort: {{ .Values.frontend.service.spec.ports.targetPort }}
