apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.auth.deployment.metadata.name }}
  namespace: {{ .Values.auth.deployment.metadata.namespace }}
spec:
  replicas: {{ .Values.auth.deployment.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.auth.deployment.spec.selector.matchLabels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.auth.deployment.spec.template.metadata.labels.app }}
    spec:
      containers:
        - name: {{ .Values.auth.deployment.spec.template.spec.containers.name }}
          image: {{ .Values.auth.deployment.spec.template.spec.containers.image }}
          imagePullPolicy: {{ .Values.auth.deployment.spec.template.spec.containers.imagePullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.auth.deployment.spec.template.spec.containers.resources.requests.cpu }}
              memory: {{ .Values.auth.deployment.spec.template.spec.containers.resources.requests.memory }}
            limits:
              cpu: {{ .Values.auth.deployment.spec.template.spec.containers.resources.limits.cpu }}
              memory: {{  .Values.auth.deployment.spec.template.spec.containers.resources.limits.memory }}
          env:
            {{- range .Values.auth.deployment.spec.template.spec.containers.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.auth.deployment.spec.template.spec.containers.ports.containerPort }}
              protocol: {{ .Values.auth.deployment.spec.template.spec.containers.ports.protocol }}
      restartPolicy: {{ .Values.auth.deployment.spec.template.spec.restartPolicy }}

