apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: {{ .Values.service.ports.name }}
      port: {{ .Values.service.ports.port }} 
      targetPort: {{ .Values.service.ports.targetPort }} 
