apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: {{ .Values.app.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
 
    spec:
      containers:
        - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.PullPolicy}}
          resources:
            cpu: {{.Values.resources.cpu.requests}}
            memory: {{.Values.resources.memory.requests}}
          env: 
            {{- range .Values.env }}
          name: {{ .name }}
          value: {{ .value | quote }}
          {{- end }}
          name: {{ .Values.app.name }}
          ports:
            - containerPort: {{ .Values.ports.containerPort }}
              protocol: {{ .Values.ports.protocol }}
      restartPolicy: {{ .Values.restartPolicy }}
